### ISSUE TITLE
About results on VOT2016

### ISSUE THREAD

**Issue by Evelyn5589** [martin-danelljan/ECO#1]
Hello ,DM

I have run the experienment on VOT2016 for several hours. And the EAO is 0.3581 on baseline , lower than 0.375 in the paper . I doubt whether the param causes the difference ?

**Comment by martin-danelljan** [comment]
Hi. We are currently investigating this issue. As mentioned, the results can vary somewhat on different computers. Are you using the mexResize function?

**Comment by Evelyn5589** [comment]
I note that you have updated the code and the info "Fixed better support for runnint without mexResize". And I also updated the repo . 

But , when I run demo_ECO_HC.m , there is still a warning :" Error when using the mexResize function. Using Matlab's interpolation function instead, which is slower." , the same warning as before. Besides , a  error  follows : Invalid MEX-file 'ECO/external_libs/mexResize/mexResize.mexa64'.
/sys/os/glnxa64/libstdc++.so.6:
version `GLIBCXX_3.4.20' not found.

Maybe the vesion of opencv is not right , I will change it and try again.
But, I have a question, can the mexResize function influence the results ? It said "Matlab's interpolation function instead, which is slower."  I have thought it maybe slower and would not decline in performance.

**Comment by Evelyn5589** [comment]
Thank you so much. I have compiled it again .
Using the mexResize function in opencv rather than matlab. It shows that it can really be quicker than before ~
And I will run it on VOT2016 again.Thank you so much.

**Comment by candy2688** [comment]
Hi, I also enconter the same problem, I just don't know how to use mexRize in opencv, when I compile mexRisize in external_lib,  there were error "opencv_core242.lib  libopencv_core242.lib" not found, should I install opencv2.4.2?

**Comment by Evelyn5589** [comment]
Hi, Martin Danelljan.Sorry to disturb you again.
I have a question ..Why the results can vary somewhat on different computers.? I have run it on GeForce GTX 1080 and Tesla K40m. The results are different. On the other hand, does the result depend on whether it runs on CPU or GPU ?

**Comment by martin-danelljan** [comment]
Hi, that is no problem.

We have not published the full GPU version of the ECO code yet. I hope to get it ready before summer. But differences on different machines probably mostly depend on that the compilations of the underlying libraries for e.g. HOG, resizing, deep features etc. are slightly different. This is the case for any tracker that is not pure Matlab code. In fact, even the results for those trackers can vary.

**Comment by Evelyn5589** [comment]
Hi , Martin Danelljan 
I have another question. About DSST, you have considered the scale and translation filter. I think it can be implemented with the angle rotation filter. For many annotations in VOT2016/17 are all rotated . This is my thought . Sorry to disturb you again...~~.  ^_^

                  
发自我的 iPhone

**Comment by martin-danelljan** [comment]
Yes, you are welcome to try! We have played around with rotation filters long in the past, but never got it to work really stable.

**Comment by Evelyn5589** [comment]
I have tried to change the output layer of CNN.But I found that when I change the layer and down sample factor to control the cell size.Sometimes it goes wrong,such as,    Output layer=[ 1   7  14]. Down sample factor=[ 4  2 1].    So, is there any restriction to these parameters ?

发自我的 iPhone

**Comment by martin-danelljan** [comment]
Did you remember to set the compressed dimensionality to something? It must contain the same number of elements as layers. For example:
cnn_params.compressed_dim = [16 32 64];

**Comment by Evelyn5589** [comment]
Hello.Dear DM,  I don't know why you have referred that the CNN feature can only be from the different layer of the same net .I think that it can also be from different nets. It's  a little. strange.

发自我的 iPhone

**Comment by martin-danelljan** [comment]
Of course multiple nets can be used. And the tracker itself supports it. The only problem is that the init_features.m has to be rewritten slightly to support this. But that is pretty easy.

**Comment by Evelyn5589** [comment]
Yes ,I found that when the multi-net was used, the compressed_dim of the two different net must be same ,or there would be an error. And it shows that the result isn't good if the multi-net is used.

发自我的 iPhone

**Comment by OuYag** [comment]
＠Evelyn5589 How can I contact you if there are some questions I need your help?Please..

**Comment by Evelyn5589** [comment]
I have replied to you in your gmail 

发自我的 iPhone
