### ISSUE TITLE
installation of submodules

### ISSUE THREAD

**Issue by nikky4D** [martin-danelljan/ECO#10]
Hi, I ran into the issues below while trying to clone the external libraries for ECO. It appears to be a failure to clone the pdollar and matconvnet libraries. Do you have any ideas to help me figure out what I should do?

`C:\Users\nkiruka\Desktop\tracking>cd ECO`

`C:\Users\nkiruka\Desktop\tracking\ECO>git submodule init`
`Submodule 'external_libs/matconvnet' (git@github.com:vlfeat/matconvnet.git) registered for path 'external_libs/matconvnet'`
`Submodule 'external_libs/pdollar_toolbox' (git@github.com:pdollar/toolbox.git) registered for path 'external_libs/pdollar_toolbox'`

`C:\Users\nkiruka\Desktop\tracking\ECO>git submodule update`
`Cloning into 'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/matconvnet'...`
`Host key verification failed.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`
`fatal: clone of 'git@github.com:vlfeat/matconvnet.git' into submodule path` `'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/matconvnet' failed`
`Failed to clone 'external_libs/matconvnet'. Retry scheduled`
`Cloning into 'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/pdollar_toolbox'...`
`Host key verification failed.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`
`fatal: clone of 'git@github.com:pdollar/toolbox.git' into submodule path` `'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/pdollar_toolbox' failed`
`Failed to clone 'external_libs/pdollar_toolbox'. Retry scheduled`
`Cloning into 'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/matconvnet'...`
`Host key verification failed.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`
`fatal: clone of 'git@github.com:vlfeat/matconvnet.git' into submodule path`
`'C:/Users/nkiruka/Desktop/tracking/ECO/external_libs/matconvnet' failed`
`Failed to clone 'external_libs/matconvnet' a second time, aborting`

**Comment by martin-danelljan** [comment]
Hi. Have you added your SSH key to github?

**Comment by nikky4D** [comment]
I believe I have. It worked well on my linux, but throws this error on my windows machine. I fixed it by just downloading the toolboxes separately using the code in ECO.
