### ISSUE TITLE
The sub-module that generates the groundtruth_rect.txt

### ISSUE THREAD

**Issue by LiuYan2333** [martin-danelljan/ECO#11]
Hello!

I'm using your code on a school project. Recently I ran the demo_ECO and found that the target was chosen in advance. So I wonder if there exists a sub-module that generates the file
 "groundtruth_rect.txt" so that I can choose an object in the first frame and track it.

Lot of thanks in advance!

**Comment by martin-danelljan** [comment]
Hi. In the example code, the first ground truth location is used as the target. Check `utils/load_video_info.m`. Here, `seq.init_rect` sets the initial target location.

**Comment by LiuYan2333** [comment]
Thanks for your answer. I've found the initial location as you suggested. However,I probably didn't make myself clear. I found  `rect_position_vis` in  implementation/tracker.m and I wanted to use this parameter to calculate the location of a target selected by  myself, but I found out that there existed a text called groundtruth_rect and the  parameters `seq` and `ground_truth` were closely related with each other in load_video_info.m and tracker.m so I couldn't transplanted the visualization module from tracker.m to load_video_info.m. I tried to track the target selected by myself but failed. I would appreciate it if you could give me more guides on this issue. Thanks.

**Comment by martin-danelljan** [comment]
I do not really understand your issue. The initial rect is simply set as 

`seq.init_rect = ground_truth(1,:);`

in `load_video_info.m`.
