### ISSUE TITLE
CPU only

### ISSUE THREAD

**Issue by Jilliansea** [martin-danelljan/ECO#12]
Hello, I want to know whether can I use this code without GPU?

**Comment by so-as** [comment]
The runfile demo_ECO_HC.m is cpu version for ECO algorirhm. So just run this script @Jilliansea

**Comment by martin-danelljan** [comment]
The GPU is only used if you set `params.use_gpu = true` in the runfile.

**Comment by Jilliansea** [comment]
@so-as  Thank you~ It runs~
