### ISSUE TITLE
Implementation in python ?

### ISSUE THREAD

**Issue by LucyLu-LX** [martin-danelljan/ECO#13]
@martin-danelljan the code runs perfect!
Is there any implementation of ECO in python?
If no, how is the workload?
It is hard for me to estimate the workload due to the additional Toolboxes. Thanks!

**Comment by LucyLu-LX** [comment]
Or C++?

**Comment by martin-danelljan** [comment]
Hi. I would like to implement this in Python, but that will probably not happen in the foreseeable future. I do not know of any python implementations.

I am mostly using standard routines, so there is not so much "hidden" code you have to write in that sense. Of course, you would need to use some other deep learning library.

**Comment by ahkarami** [comment]
You can use PyTorch for it (like Py-MDNet code).
