### ISSUE TITLE
When i run install.m ,Wrong:“Error using mex incorrectly” 

### ISSUE THREAD

**Issue by zh1049** [martin-danelljan/ECO#14]
Hello!
   Now,I'm using your code to learn tracking. following your methods,  when I run the code of install.m, prompting  an error  ,this ：
    ECO-master\external_libs\matconvnet\matlab\src\bits\impl/dispatcher.hpp:50:16:   error: request for member 'tensor' in 'h',which is of non-class type 'int'
     if ((int)h.tensor && !(int)(h.tensor->isNull())) {

**Comment by zh1049** [comment]
Lot of thanks in advance!

**Comment by martin-danelljan** [comment]
What OS and compiler are you using? And what version of matconvnet?

This seems to be an error that is purely related to the compilation of matconvnet. You should refer to their Github as well.

**Comment by zh1049** [comment]
Before I used window system and Matlab2015b to compile the code.  Today  I try to  use Linux to compile it(replaced the version of GCC). Now, It is right.   Thank you very much.

**Comment by martin-danelljan** [comment]
Happy to hear!
