### ISSUE TITLE
Install.m Error 

### ISSUE THREAD

**Issue by pvbhanuteja** [martin-danelljan/ECO#17]
https://i.imgur.com/6sZzPM9.png

i am getting this error when i am trying to run install.m

'cl.exe' is not recognized as an internal or external command, 
operable program or batch file. 
Error using vl_compilenn>check_clpath (line 599)
Unable to find cl.exe

Error in vl_compilenn (line 417)
    cl_path = fileparts(check_clpath()); % check whether cl.exe in path

Error in install (line 33)
        vl_compilenn;

**Comment by SignalImageCV** [comment]
what is your matlab version?this problem may result from the MatConvnet

**Comment by SignalImageCV** [comment]
i replace the matconvnet in ECO with old version matconvnet v1.0-beta19, and it is ok!

**Comment by martin-danelljan** [comment]
The best thing is to use the version of matconvnet specified in the submodule. I.e., the one you get the first time you run `git submodule update`.
