### ISSUE TITLE
about the “-1” in ‘ECO/utils/get_sequence_info.m’

### ISSUE THREAD

**Issue by 110awesome** [martin-danelljan/ECO#20]
dear ；
 I'm sorry to disturb, I do not understand why to ask for the center position must to  -1,and it has much influence to the results. 
I am looking forward your answer.
![image](https://user-images.githubusercontent.com/20498205/33978793-5cba728e-e0dc-11e7-846a-af6d01ae5cb0.png)

**Comment by martin-danelljan** [comment]
Note that the bottom left coordinate has to be bl = (tl_x + w - 1, tl_y + h - 1) where tl is the top left coordinate and w, h are the width and height.
