### ISSUE TITLE
Can ECO be used for multiple object tracking?

### ISSUE THREAD

**Issue by Shaun-Zhang** [martin-danelljan/ECO#21]
Hi,dalao MD :
I`m sorry to disturb, but I just wondering how to init the tracker for multiple object tracking in one video in your code.

**Comment by ZhentangHe** [comment]
I have the same question.

**Comment by martin-danelljan** [comment]
Hey. Thanks for your interest. The ECO tracker can be used as a component in a mult-target tracking framework. But it in not a multi-target tracker on its own. Of course you can run several independent ECO trackers in parallel to track several objects at once.
