### ISSUE TITLE
when I run demo_ECO.m ，there is a question，can you help me？

### ISSUE THREAD

**Issue by Tomingz** [martin-danelljan/ECO#22]
The error was:
MEX-file '/home/zl/software/ECO/external_libs/mexResize/mexResize.mexa64' is useless:
lack of '/usr/local/lib/libopencv_core.so.2.4->/home/zl/software/ECO/external_libs/mexResize/mexResize.mexa64' symbol
'_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm'
lack of '/usr/local/lib/libopencv_core.so.2.4->/home/zl/software/ECO/external_libs/mexResize/mexResize.mexa64' symbol
'_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofEPKcmm'
lack of  '/usr/local/lib/libopencv_core.so.2.4->/home/zl/software/ECO/external_libs/mexResize/mexResize.mexa64' symbol
'_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm'
lack of  '/usr/local/lib/libopencv_core.so.2.4->/home/zl/software/ECO/external_libs/mexResize/mexResize.mexa64' symbol
'_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm'

I have already installed opencv2.4.13 in my ubuntu before，Is opencv path conflict?

**Comment by fybaft2012** [comment]
Hi Tomingz, did you solve the problem? When I run the code with re-compiled mexResize.mexa64,  it gives the error message:
Invalid MEX-file '/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64':
Missing dependent shared libraries:
'libopencv_core.so.2.4' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
'libopencv_imgproc.so.2.4' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'

Missing symbol '_ZN2cv11_InputArrayC1ERKd' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv11_InputArrayC1ERKNS_3MatE' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv12_OutputArrayC1ERNS_3MatE' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv22SparseMatConstIteratorC1EPKNS_9SparseMatE' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv22SparseMatConstIteratorppEv' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv3Mat10deallocateEv' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv3Mat5setToERKNS_11_InputArrayES3_' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv3Mat6createEiPKii' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv3Mat8copySizeERKS0_' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv3MatC1EiPKiiPvPKm' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv5mergeERKSt6vectorINS_3MatESaIS1_EERKNS_12_OutputArrayE' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv5splitERKNS_3MatERSt6vectorIS0_SaIS0_EE' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv6resizeERKNS_11_InputArrayERKNS_12_OutputArrayENS_5Size_IiEEddi' required
by '/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv7compareERKNS_11_InputArrayES2_RKNS_12_OutputArrayEi' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv7MomentsC1Ev' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv8fastFreeEPv' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv9SparseMat3ptrEiibPm' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZN2cv9SparseMat6createEiPKii' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZNK2cv3Mat1tEv' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'
Missing symbol '_ZNK2cv3Mat9convertToERKNS_12_OutputArrayEidd' required by
'/home/aiserver/tracking_module/external_libs/mexResize/mexResize.mexa64'.

Could you help me what should I do to solve this error?

**Comment by goutamgmb** [comment]
Hi,

It seems opencv is not linked correctly.

Can you post the output of 
1) `ldd mexResize.mexa64`  from ECO/external_libs/mexResize
2)  `!ldd mexResize.mexa64`  (from the same directory, but run this command from matlab)

**Comment by fybaft2012** [comment]
When I run first in ubuntu terminal is gives following message:
aiserver@aiserver-desktop:~/tracking_module/external_libs/mexResize$ ldd mexResize.mexa64
	linux-vdso.so.1 =>  (0x00007ffe6ede5000)
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fde5acd1000)
	/usr/lib/x86_64-linux-gnu/libprotobuf.so.9 (0x00007fde5a9b3000)
	libopencv_core.so.2.4 => not found
	libopencv_imgproc.so.2.4 => not found
	libmx.so => not found
	libmex.so => not found
	libmat.so => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fde5a6aa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fde5a494000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fde5a277000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fde59ead000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fde5b264000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fde59c93000)

When I run second line in matlab command, it shows:
!ldd mexResize.mexa64
	linux-vdso.so.1 =>  (0x00007ffce61ed000)
	libopencv_core.so.2.4 => not found
	libopencv_imgproc.so.2.4 => not found
	libmx.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmx.so (0x00007ffab2adb000)
	libmex.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmex.so (0x00007ffab28a4000)
	libmat.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmat.so (0x00007ffab2649000)
	libstdc++.so.6 => /usr/local/MATLABT/R2017b/sys/os/glnxa64/libstdc++.so.6 (0x00007ffab2337000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffab202e000)
	libgcc_s.so.1 => /usr/local/MATLABT/R2017b/sys/os/glnxa64/libgcc_s.so.1 (0x00007ffab1e18000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffab1bfb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffab1831000)
	libmwi18n.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwi18n.so (0x00007ffab14ea000)
	libut.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libut.so (0x00007ffab1206000)
	libmwfl.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwfl.so (0x00007ffab0e3e000)
	libmwfoundation_usm.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwfoundation_usm.so (0x00007ffab0c1d000)
	libboost_log.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_log.so.1.56.0 (0x00007ffab0940000)
	libboost_system.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_system.so.1.56.0 (0x00007ffab073d000)
	libboost_thread.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_thread.so.1.56.0 (0x00007ffab051c000)
	libmwcpp11compat.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwcpp11compat.so (0x00007ffab02fe000)
	libicuuc.so.56 => /usr/local/MATLABT/R2017b/bin/glnxa64/libicuuc.so.56 (0x00007ffaaff60000)
	libtbb.so.2 => /usr/local/MATLABT/R2017b/bin/glnxa64/libtbb.so.2 (0x00007ffaafd15000)
	libtbbmalloc.so.2 => /usr/local/MATLABT/R2017b/bin/glnxa64/libtbbmalloc.so.2 (0x00007ffaafac3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffaaf8a9000)
	libmwservices.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwservices.so (0x00007ffaaf262000)
	libmwmpath.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmpath.so (0x00007ffaaefd5000)
	libmwm_dispatcher.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwm_dispatcher.so (0x00007ffaaecc8000)
	libmwgenerate_diag_message.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwgenerate_diag_message.so (0x00007ffaaeac0000)
	libhdf5.so.8 => /usr/local/MATLABT/R2017b/bin/glnxa64/libhdf5.so.8 (0x00007ffaae62f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffab307e000)
	libmwresource_core.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwresource_core.so (0x00007ffaae42d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffaae229000)
	libboost_filesystem.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_filesystem.so.1.56.0 (0x00007ffaae013000)
	libexpat.so.1 => /usr/local/MATLABT/R2017b/bin/glnxa64/libexpat.so.1 (0x00007ffaaddeb000)
	libicui18n.so.56 => /usr/local/MATLABT/R2017b/bin/glnxa64/libicui18n.so.56 (0x00007ffaad964000)
	libicuio.so.56 => /usr/local/MATLABT/R2017b/bin/glnxa64/libicuio.so.56 (0x00007ffaad757000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffaad54f000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007ffaad317000)
	libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007ffaad109000)
	libboost_date_time.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_date_time.so.1.56.0 (0x00007ffaacef8000)
	libboost_regex.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_regex.so.1.56.0 (0x00007ffaacbe8000)
	libboost_serialization.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_serialization.so.1.56.0 (0x00007ffaac988000)
	libunwind.so.8 => /usr/local/MATLABT/R2017b/bin/glnxa64/libunwind.so.8 (0x00007ffaac769000)
	libboost_chrono.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_chrono.so.1.56.0 (0x00007ffaac563000)
	libicudata.so.56 => /usr/local/MATLABT/R2017b/bin/glnxa64/libicudata.so.56 (0x00007ffaaab7d000)
	libmwlivecode.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwlivecode.so (0x00007ffaaa934000)
	libmwcppmicroservices.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwcppmicroservices.so (0x00007ffaaa70b000)
	libmwregexp.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwregexp.so (0x00007ffaaa4c1000)
	libmwmlutil.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmlutil.so (0x00007ffaa9c62000)
	libmwsettingscore.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwsettingscore.so (0x00007ffaa9817000)
	libmwms.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwms.so (0x00007ffaa9330000)
	libmwkeybrd.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwkeybrd.so (0x00007ffaa912d000)
	libboost_iostreams.so.1.56.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libboost_iostreams.so.1.56.0 (0x00007ffaa8f19000)
	libCppMicroServices.so.3.0.0 => /usr/local/MATLABT/R2017b/bin/glnxa64/libCppMicroServices.so.3.0.0 (0x00007ffaa8c18000)
	libmwflstoragevfs.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflstoragevfs.so (0x00007ffaa8949000)
	libmwstorageshlibstoragesys.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwstorageshlibstoragesys.so (0x00007ffaa8707000)
	libxerces-c-3.1.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libxerces-c-3.1.so (0x00007ffaa8055000)
	libmwsearch_path_impl.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwsearch_path_impl.so (0x00007ffaa7d88000)
	libmwddux.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwddux.so (0x00007ffaa7b6a000)
	libmwxmlcore.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwxmlcore.so (0x00007ffaa78f4000)
	libmwstring_matrix.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwstring_matrix.so (0x00007ffaa76cc000)
	libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007ffaa74a5000)
	libmwopccore.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwopccore.so (0x00007ffaa724d000)
	libmwopcmodel.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwopcmodel.so (0x00007ffaa6f7a000)
	libmwopczippackage.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwopczippackage.so (0x00007ffaa6d54000)
	libmwopcmwservices.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwopcmwservices.so (0x00007ffaa6af1000)
	libmwfoundation_extdata_array.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwfoundation_extdata_array.so (0x00007ffaa68cb000)
	libmwflnetwork.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflnetwork.so (0x00007ffaa6621000)
	libmwflstorageprovider.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflstorageprovider.so (0x00007ffaa63dd000)
	libmwflstorageevents.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflstorageevents.so (0x00007ffaa61c0000)
	libmwstoragesharedlib.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwstoragesharedlib.so (0x00007ffaa5fa4000)
	libmwcwf_interface.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwcwf_interface.so (0x00007ffaa5d46000)
	libmwmatlabstoragesystem.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmatlabstoragesystem.so (0x00007ffaa5b43000)
	libmwsearch_path_events.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwsearch_path_events.so (0x00007ffaa5933000)
	libmwsearch_path_interfaces.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwsearch_path_interfaces.so (0x00007ffaa572d000)
	libmwsearch_path_utilities.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwsearch_path_utilities.so (0x00007ffaa5514000)
	libmwstoragefilefolderobserver.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwstoragefilefolderobserver.so (0x00007ffaa528e000)
	libmwmvm.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmvm.so (0x00007ffaa4d72000)
	libmwmcos.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmcos.so (0x00007ffaa4b19000)
	libmwflcrypto.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflcrypto.so (0x00007ffaa48eb000)
	libmwflcryptoutils.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflcryptoutils.so (0x00007ffaa46df000)
	libmwflcryptocryptopp.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwflcryptocryptopp.so (0x00007ffaa4218000)
	libminizip.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libminizip.so (0x00007ffaa400a000)
	libmwmst.so => /usr/local/MATLABT/R2017b/bin/glnxa64/libmwmst.so (0x00007ffaa3cae000)


By the way, in order to avoid opencv version compatible issue (as some blog said), before recompile mexResize fun, I uninstalled the opencv from my ubuntu, and only use the file which you provided in the mexResize folder. it gives me this error. Could you find out what happened?

**Comment by cploveflower** [comment]
when I run the install in the matlab ,it have the error:
 Build routine for mtimesx
... Checking for PC
... Finding path of mtimesx C source code files
... Found file mtimesx.c in C:\Users\cpp\ECO\external_libs\mtimesx\mtimesx.c
... Found file mtimesx_RealTimesReal.c in C:\Users\cpp\ECO\external_libs\mtimesx\mtimesx_RealTimesReal.c
A C/C++ compiler has not been selected with mex -setup
error:install (line 10)
    mtimesx_build;

can you tell me how to run the install with no error？thank you!

**Comment by Pen9uin** [comment]
> when I run the install in the matlab ,it have the error:
> Build routine for mtimesx
> ... Checking for PC
> ... Finding path of mtimesx C source code files
> ... Found file mtimesx.c in C:\Users\cpp\ECO\external_libs\mtimesx\mtimesx.c
> ... Found file mtimesx_RealTimesReal.c in C:\Users\cpp\ECO\external_libs\mtimesx\mtimesx_RealTimesReal.c
> A C/C++ compiler has not been selected with mex -setup
> error:install (line 10)
> mtimesx_build;
> 
> can you tell me how to run the install with no error？thank you!

hey, i got same error, i found a way to solve
run “mex -setup C++” in matlab, then follow the guide
then run the demo successfully.

**Comment by martin-danelljan** [comment]
@cploveflower The error message tells you what to do, which is exactly what @Pen9uin said.
