### ISSUE TITLE
Is ECO suitable for feature point tracking?

### ISSUE THREAD

**Issue by tiancivalen** [martin-danelljan/ECO#25]
Hi ! I am curious about whether ECO can be used for feature point tracking. Could you please give some instructions on how to use it for feature point tracking if possible? Thanks!

**Comment by martin-danelljan** [comment]
Check our [CCOT paper](http://www.cvl.isy.liu.se/research/objrec/visualtracking/conttrack/C-COT_ECCV16.pdf), there feature point tracking is described. You can modify the ECO or CCOT code to do that.
