### ISSUE TITLE
when i integrate the eco with vot toolkits(5.0.2) there some error

### ISSUE THREAD

**Issue by guxiwuruo** [martin-danelljan/ECO#27]
![default](https://user-images.githubusercontent.com/25118059/37276708-81a91786-261d-11e8-9a7e-e6b82ab64a7d.PNG)
use the file you provide
and if i set the repetition of the realtime is 1,there is no problem 
when i debug this, i find the T1 and T2 is empty
maybe i could spend alot time on the vot toolkit to understand the problem
could you help me about this ?

**Comment by JWarlock** [comment]
Hi, there!
I am using vot-toolkit-master 5.0.2 TraX 1.1.2 MATLABR2017a  ubuntu 16.04 on a server.
And I have been trying to integrate the  ECO tracker into vot , following   instructions. 
I Copy the configuration file tracker_ECO.m to my VOT workspace and set the path to the ECO repository inside it.
However, when I try to evaluate it on vot2017 dataset,  an error occurred:

> 

> run_experiments
> Initializing workspace ...
> Verifying native components ...
> 
> Experiment baseline
>   Tracker ECO
>     Sequence ants1
>       Repetition 1
>       Tracker execution interrupted: Did not receive response.
> Error using traxclient
> Did not receive response.
> Error in tracker_run (line 77)
>     data = traxclient(tracker.command, callback, ...
> Error in experiment_supervised (line 68)
>     data = tracker_run(tracker, @callback, data);
> Error in tracker_evaluate (line 57)
>  [files, metadata] = experiment_function(tracker, sequence, directory,
>         parameters, scan);
> Error in workspace_evaluate>execute_iterator (line 127)
>         tracker_evaluate(event.tracker, event.sequence, event.experiment);
> Error in iterate (line 65)
>             context = iterator(event, context);
> Error in workspace_evaluate (line 93)
> context = iterate(experiments, trackers, sequences, 'iterator', iterator,
> 'context', context);
> Error in run_experiments (line 10)
> workspace_evaluate(tracker, sequences, experiments);
> 
 I am new to vot-toolkit. I follow the instructions of www.votchallenge.net/howto/integration.html and the NCC tracker works just fine on vot-test dataset.
when I checked the error message, I found that with surprise:

> 
> a=load('ECO_VOT2016_DEEP_settings_180409_1613.mat');
>  err=a.err
> err = 
>   MException with properties:
>     identifier: 'MATLAB:UndefinedFunction'
>        message: 'Undefined function 'vl_simplenn_tidy' for input arguments of type 'struct'.'
>          cause: {}
>          stack: [5×1 struct]

However, I did add the path of MatConvNet( I'm using MatConvNet 1.0-beta25 with CUDA8.0 and Cudnn v6) by vl_setupnn.  When I simply tried to load imagenet-vgg-m-2048 net and then use vl_simplenn_tidy manually , everything worked just fine!!!  
I can't understand it. why? please help !

**Comment by martin-danelljan** [comment]
@guxiwuruo Sorry for the delay. I think this is an issue with the VOT toolkit.

@JWarlock ECO currently does not support the newest version of MatConvNet. Try the version that is included as a submodule: `git submodule update`
