### ISSUE TITLE
demo_ECO no work

### ISSUE THREAD

**Issue by eeric** [martin-danelljan/ECO#3]
Error using fliplr (line 18)
X must be a 2-D matrix.
Error in cfft2 (line 19)
        xf(end,:,:,:) = conj(fliplr(xf(1,:,:,:)));
Error in tracker (line 297)
        xlf = cellfun(@cfft2, xlw, 'uniformoutput', false);
Error in testing_ECO (line 133)
results = tracker(params);
Error in demo_ECO (line 13)
results = testing_ECO(seq);

**Comment by eeric** [comment]
above problem occured in windows system, and then it succeeded in linux system.

**Comment by martin-danelljan** [comment]
What version of Matlab are you using?

**Comment by eeric** [comment]
2014a
in addition, speed is 0.83fps using demo_ECO.m, I infered it didn't work to gpu. 
so how to gpu.

**Comment by martin-danelljan** [comment]
Your initial issue should now be fixed. Also GPU support has been added in this version.
