### ISSUE TITLE
Can I use live video stream to track?

### ISSUE THREAD

**Issue by wastacat** [martin-danelljan/ECO#32]
Hi Martin,

I use testing_ECO_HC.m to test my datasets , but I want combine with detectors to do real-time object detection & tracking . Can you give me some suggestions ?

Thanks in advance

**Comment by martin-danelljan** [comment]
Hi. The current version must be restructured a bit to allow this. The best way is probably to make the code object oriented, having a tracker class that includes the state. Then have a "track" and "update" interface for this class.

We will probably release a version that can also do live streaming. But this is likely due after summer unfortunately.

**Comment by alexanderfrey** [comment]
Do you have an update whether you proceeded implementing support for live video stream ?

**Comment by martin-danelljan** [comment]
Hi. Yes, there is in our new pytorch-based framework [pytracking](https://github.com/visionml/pytracking).
