### ISSUE TITLE
About Multi-tracking Problem

### ISSUE THREAD

**Issue by HoracceFeng** [martin-danelljan/ECO#34]
HI @martin-danelljan ,

Thanks for your impressive work! I just successfully run the demo_ECO_HC in matlab 2014b and it seems perfect. However, I notice that it only tracks one person, so I am curious about the performance in multi-tracking task. 

Also, I am interested in using this tracker in other sequences. I am not sure but it seems that your demo is just read the frame and bbox-info in 'sequence' file? So how can I try it by using my own sequences? Quite confuse when I find out the 'tracker.m' but cannot figure out ways to import sequences... I am a newbie in using Matlab ...

Thx!

**Comment by martin-danelljan** [comment]
Hi. You could extend it to multiple targets by running several trackers at once. When it comes to other sequences, you should integrate this yourself. You see how it can be done with the example sequence that is included.
