### ISSUE TITLE
About the git submodule update

### ISSUE THREAD

**Issue by cploveflower** [martin-danelljan/ECO#35]
Hello,@martin-danelljan
when I come to the git submodule update,it will have a error:
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:vlfeat/matconvnet.git' into submodule path 'C:/Users/cpp/ECO/e            xternal_libs/matconvnet' failed
Failed to clone 'external_libs/matconvnet' a second time, aborting

then I change the url in gitmudule ,and when I git submodule update again,it still have a error:
 fatal: not a git repository: C:/Users/cpp/ECO/external_libs/pdollar_toolbox/../../.git/modules/external_libs/pdollar_toolbox
Failed to clone 'external_libs/pdollar_toolbox'. Retry scheduled
BUG: submodule considered for cloning, doesn't need cloning any more?
Submodule path 'external_libs/matconvnet': checked out '6221423ac64067426bbaa2ffd31557523258d1fe'
fatal: not a git repository: C:/Users/cpp/ECO/external_libs/pdollar_toolbox/../../.git/modules/external_libs/pdollar_toolbox
Unable to fetch in submodule path 'external_libs/pdollar_toolbox'
fatal: not a git repository: C:/Users/cpp/ECO/external_libs/pdollar_toolbox/../../.git/modules/external_libs/pdollar_toolbox
fatal: not a git repository: C:/Users/cpp/ECO/external_libs/pdollar_toolbox/../../.git/modules/external_libs/pdollar_toolbox
fatal: not a git repository: C:/Users/cpp/ECO/external_libs/pdollar_toolbox/../../.git/modules/external_libs/pdollar_toolbox
Fetched in submodule path 'external_libs/pdollar_toolbox', but it did not contain 1a3c9869033548abb0c7a3c2aa6a7902c36f39c2. Direct fetching of that commit failed.

I don't know why,can you help me?

**Comment by yangkai12** [comment]
I have the same issue,how to solve the issue?

**Comment by martin-danelljan** [comment]
I think you just need to add your SSH key to your github account.
