### ISSUE TITLE
Error when I run demo_ECO_gpu.m？

### ISSUE THREAD

**Issue by trikim** [martin-danelljan/ECO#38]
I have succeed to run the demo_ECO.m and demo_ECO_HC.m file. However, I have encountered these errors.
Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 300)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

Error in get_cnn_layers (line 23)
    cnn_feat = vl_simplenn(fparams.net, im,[],[],'CuDNN',true, 'Mode', 'test');

Error in extract_features (line 59)
        feature_map(ind:ind+num_blocks-1) = feat.getFeature(img_samples{img_sample_ind},
        feat.fparams, gparams);

Error in tracker (line 347)
        xl = extract_features(im, sample_pos, currentScaleFactor, features, global_fparams,
        feature_extract_info);

Error in testing_ECO_gpu (line 129)
results = tracker(params);

Error in demo_ECO_gpu (line 13)
results = testing_ECO_gpu(seq);

Could you help to fix these problems?

**Comment by whoisalan** [comment]
i met the same problems

**Comment by vivinousi** [comment]
I was able to fix this error by switching the order in which the matconvnet directories are added to the path in setup_path.m (lines 20-22), as:
```
addpath([pathstr '/external_libs/matconvnet/matlab']);
addpath([pathstr '/external_libs/matconvnet/matlab/simplenn']);
addpath([pathstr '/external_libs/matconvnet/matlab/mex/']);
```

**Comment by martin-danelljan** [comment]
Hmm interesting. Note that I have only verified that it works with the older version of matconvnet, i.e. the one you get by running 'git submodule update'.

**Comment by helloxueen** [comment]
> 
> 
> I was able to fix this error by switching the order in which the matconvnet directories are added to the path in setup_path.m (lines 20-22), as:
> 
> ```
> addpath([pathstr '/external_libs/matconvnet/matlab']);
> addpath([pathstr '/external_libs/matconvnet/matlab/simplenn']);
> addpath([pathstr '/external_libs/matconvnet/matlab/mex/']);
> ```

what GPU version did you use?8.0 or 7.5? Beacuse I met the same error when I use GPU 8.1 even if the matconvnet directories are added to the path!!!! Any else method???

**Comment by martin-danelljan** [comment]
Have you compiled matconvnet properly?

**Comment by zhyply** [comment]
> 
> 
> I was able to fix this error by switching the order in which the matconvnet directories are added to the path in setup_path.m (lines 20-22), as:
> 
> ```
> addpath([pathstr '/external_libs/matconvnet/matlab']);
> addpath([pathstr '/external_libs/matconvnet/matlab/simplenn']);
> addpath([pathstr '/external_libs/matconvnet/matlab/mex/']);
> ```
I have compile matconvnet-GPU already(win10+vs2017+cuda9.2+cudnn7.6), but the demo_ECO_gpu.m goes error by "An input is not a numeric array".
I try @vivinousi solution method, is work, program run perfect. nice try!!!

**Comment by martin-danelljan** [comment]
Thank you for the solution. It is fixed in the code now.
