### ISSUE TITLE
test on vot2017

### ISSUE THREAD

**Issue by zhanglichao** [martin-danelljan/ECO#4]
hi Martin,

I'm trying to run_experiment on vot2017 using trax, but it replied 'don't get response'. Maybe some slightly detailed mismatches for the trax protocol?

Thanks for your reply in advance.

best,
Lichao

**Comment by martin-danelljan** [comment]
So VOT2017 works now? Was it anything special that i missed?

Regards,
Martin

**Comment by zhanglichao** [comment]
hi Martin,

You're so nicely to ask. Actually, it still works in mistake.
1. I run_test in the vot-workspace, but finally it replies the errors in details:
VOT2016_DEEP_settings(seq, [], []);
@@TRAX:hello "trax.image=path;" "trax.region=polygon;" "trax.version=1" 
CLIENT: Tracker process ID: 15886
CLIENT: Connection with tracker established.
@@TRAX:initialize "file:///home/lichao/Documents/tracking/vot/vot2017/vot-toolkit/vot-workspace/sequences/ants1/00000001.jpg" "137.2100,458.3600,156.8300,460.7800,148.3500,529.4100,128.7200,526.9900" 
CLIENT: Timeout reached. Stopping tracker process ...
CLIENT: Trying to stop process using protocol.
@@TRAX:quit 
CLIENT: Trying to terminate process nicely.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Trying to stop process using protocol.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Trying to stop process using protocol.
Tracker execution interrupted: Did not receive response.
Error using traxclient
Did not receive response.

Error in tracker_run (line 77)
    data = traxclient(tracker.command, callback, ...

Error in workspace_test (line 53)
            tracker_run(tracker, @callback, data);

Error in run_test (line 10)
workspace_test(tracker, sequences);

2. Also run_experiment replies:
Error using traxclient
Did not receive response.

Thanks so much & best,
Lichao

**Comment by martin-danelljan** [comment]
Are any error reports generated by the tracker? Check the VOT/error_reports folder and display them with getReport(err) in matlab.

**Comment by zhanglichao** [comment]
I checked VOT_integration, but no error_reports folder is even made. perhaps it even not went that step...

best

**Comment by martin-danelljan** [comment]
Check this:
1. Make sure you have the latest version of ECO (current master branch) and VOT toolkit.
2. Have you tried do run with and without GPU? 
3. Also try to run with hand-crafted features.
4. Have you been able to integrate any other trackers into VOT using the trax protocol?

**Comment by zhanglichao** [comment]
hi Martin,

It works in HC_settings. I think something wrong in my matconvnet library, as I use my matconvnet instead of the matconvnet in external_libs. Of course I changes the path in setup_paths and it works for demo_ECO_gpu test. But when it run in vot, it failed like the above errors.

best

**Comment by cybertk** [comment]
@zhanglichao Perhaps logs can give more details, they are located at `$vot_workspace/logs` and `$eco_repo_path/VOT_integration/error_reports`.

**Comment by zhanglichao** [comment]
OK, thanks very much. I'll check it!
best

**Comment by zhanglichao** [comment]
@cybertk The logs Feedback these, but I don't find where's the problem...
[Warning: Duplicate directory name: /usr/local/MATLAB/R2016a/toolbox/local] 
 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
VOT2016_DEEP_settings(seq, [], []);
@@TRAX:hello "trax.image=path;" "trax.region=polygon;" "trax.version=1" 
@@TRAX:initialize "file:///home/lichao/Documents/tracking/vot/vot2017/vot-toolkit/vot-workspace/sequences/ants1/00000001.jpg" "137.2100,458.3600,156.8300,460.7800,148.3500,529.4100,128.7200,526.9900" 
@@TRAX:quit 

And also i didn't find error_reports in $eco_repo_path/VOT_integration/?

Maybe u can give me some valuable solutions.
Thanks at advance!

**Comment by cybertk** [comment]
From your logs, 

1. The tracker is already started, as no $eco_repo_path/VOT_integration/error_reports
2. The tracker received a `quit` signal due to timeout(hint from your question)

I would increase the timeout if sit in your position. The default timeout is 30s, modify by adding following line into your `configuration.m` in your workspace.

```
set_global_variable('trax_timeout', 30);
```

**Comment by zhanglichao** [comment]
Yes, you're perfectly nice! It works now!

best,
Lichao
