### ISSUE TITLE
C++ implementation of ECO

### ISSUE THREAD

**Issue by rockkingjy** [martin-danelljan/ECO#40]
Your work is really great, and I am implementing your [ECO using C++](https://github.com/rockkingjy/OpenTracker), try to speed up as much as possible, but still have a question of why you arrange your feature matrix like that in non-GPU version with lots of rearrangements of the order, is that for speed? GPU version matrix is quite clear.

**Comment by martin-danelljan** [comment]
Hi! Thank you very much. Yours too, nice work!
Sorry for the late response. But yes, most of the permutations are done considering speed. But I am not sure that they are the most optimal ones. It depends on how your data is arranged of course.
