### ISSUE TITLE
Error when using mexResize

### ISSUE THREAD

**Issue by chenyjade** [martin-danelljan/ECO#41]
I have already run `compile `in external_libs/mexResize
But when I try to use mexReize, there is an ERROR:

> Invalid MEX-file '/mydir/data/ECO-master/external_libs/mexResize/mexResize.mexa64':
> '/mydir/data/ECO-master/external_libs/mexResize/mexResize.mexa64' is not a valid shared library..

I tried `!ldd mexResize` in matlab, and the output was:

> ./mexResize.mexa64: /usr/local/Mathworks/R2017b/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./mexResize.mexa64)
> 	linux-vdso.so.1 =>  (0x00007ffdba523000)
> 	libopencv_core.so.2.4 => not found
> 	libopencv_imgproc.so.2.4 => not found

I'm not sure what should I do now to run the mexResize, could you help me please?

**Comment by martin-danelljan** [comment]
Hi. Which OS and version of Matlab du you use? Were there any errors during compilation?

**Comment by chenyjade** [comment]
Matalb R2017b with Ubuntu 16.04. No Errors but one warning
```
>> compile
Building with 'g++'.
Warning: You are using gcc version '5.4.0'. The version of gcc is not supported. The version currently
supported with MEX is '4.9.x'. For a list of currently supported compilers see:
http://www.mathworks.com/support/compilers/current_release. 
> In compile (line 11) 
MEX completed successfully.
```
I have fixed 
`./mexResize.mexa64: /usr/local/Mathworks/R2017b/sys/os/glnxa64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by ./mexResize.mexa64)`
 by making a soft link between `/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21`  and `/usr/local/Mathworks/R2017b/sys/os/glnxa64/libstdc++.so.6`
but libopencv is still not found whatever I tried.

More seriously, when executing the function `hann`, there was an error  `libnssutil3.so: version 'NSSUTIL_3.12.5' not found` .
 I have tried to upgrade libnss3, and my matlab crashed after that (when executing `hann`)
It seems that there are something wrong with my matlab and linux environment and I'm trying to find it out :(

**Comment by martin-danelljan** [comment]
Hmm, have not seen this error before. Might be some problem with your matlab as you say. Anyway, the tracker should work even without mexResize, it automatically checks if it is working or not. If not, it will use the corresponding matlab function (which is slightly slower).
