### ISSUE TITLE
problem about testing ECO on OTB-2015

### ISSUE THREAD

**Issue by NeverMoreLCH** [martin-danelljan/ECO#43]
Hi, Martin,

Your work is really, really great, and I want to ask some questions.
In your paper, the success plot of OPE of ECO is 0.700, ECO-HC is 0.650, C-COT is 0.690, Staple is 0.584. But when I test these modles on OTB-2015, I get the result ECO is 0.688, ECO-HC is 0.635, C-COT is 0.671, Staple is 0.582. You can see that my result is a bit lower than yours. Could you give me some suggestions to increase those values?
![1quality_plot_overlap_ope_auc](https://user-images.githubusercontent.com/26295015/46015405-ce4d4300-c104-11e8-885a-d14e08e47f2b.png)

Thank you very much.

**Comment by martin-danelljan** [comment]
Hi,

Thank you for your question. So one issue might be that the evaluation framework you are using does not calculate the AUC accurately enough. Try to increase the number of overlap thresholds that the overlap precision is calculated for. This will give you a more accurate integration of the curve.

Best regards,
Martin

**Comment by NeverMoreLCH** [comment]
> Hi,
> 
> Thank you for your question. So one issue might be that the evaluation framework you are using does not calculate the AUC accurately enough. Try to increase the number of overlap thresholds that the overlap precision is calculated for. This will give you a more accurate integration of the curve.
> 
> Best regards,
> Martin

Thanks for your reply, and your suggestion really work.
