### ISSUE TITLE
some questions about the DSST

### ISSUE THREAD

**Issue by brealisty** [martin-danelljan/ECO#45]
the code:
`
im_patch_scale = getScaleSubwindow(im, pos, base_target_sz, scale_factor*scale_factors, scale_window, scale_model_sz, p.hog_scale_cell_size);
 xsf = fft(im_patch_scale,[],2);
`

why the 33 scales multiply the scale_window(shape is 1*33) respectively? It means the farther away 'base_target_sz' the maller probability? Especially, scale_window(1) = scale_window(end) = 0, why don't delete these two scales?

fft(X, [], 2), the arg '2' it means fft by row, but we konw each column of 'im_patch_scale' is a scale. so, why don't set the arg '1' to fft by column for a scale image? PLS.

**Comment by martin-danelljan** [comment]
You are right, we could probably remove the first and last scale. For the second question: we want to do the convolution in the scale dimension. Therefore we have the '2'.
