### ISSUE TITLE
How to deploy ECO into cloud 

### ISSUE THREAD

**Issue by alexanderfrey** [martin-danelljan/ECO#46]
Hello,

thanks for your excellent work. 

My question is how to deploy an instance of ECO onto a cloud service like AWS or azure ? Is this even possible with Matlab code ? 

Thanks for your help !
Alexander

**Comment by martin-danelljan** [comment]
I think you can create a Matlab [standalone](https://es.mathworks.com/help/compiler/create-and-install-a-standalone-application-from-matlab-code.html).
