### ISSUE TITLE
Error when i run vl_testnn('gpu',true)?

### ISSUE THREAD

**Issue by fongdier** [martin-danelljan/ECO#47]
---------------------------------------------------------------------
             Bus error detected at Fri Nov 16 20:06:56 2018
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Current Visual      : 0x47 (class 4, depth 24)
  Default Encoding    : UTF-8
  Deployed            : false
  GNU C Library       : 2.23 stable
  Host Name           : fyj-B85-HD3
  MATLAB Architecture : glnxa64
  MATLAB Entitlement ID: 6257193
  MATLAB Root         : /usr/local/MATLAB/R2016b
  MATLAB Version      : 9.1.0.441655 (R2016b)
  OpenGL              : hardware
  Operating System    : Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64
  Processor ID        : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11906000), display :0

Fault Count: 1

Abnormal termination:
Bus error

**Comment by martin-danelljan** [comment]
This is an issue with matconvnet. Please consult them. Try running on CPU instead.
