### ISSUE TITLE
About some problems of sh

### ISSUE THREAD

**Issue by Lrrixiang** [martin-danelljan/ECO#52]
sh = mtimesx(samplesf{k1}, permute(hf{k1}, [3 4 1 2]), 'speed');
sh(:,1,1+pad_sz{k}(1):end-pad_sz{k}(1), 1+pad_sz{k}(2):end) = ...
        sh(:,1,1+pad_sz{k}(1):end-pad_sz{k}(1), 1+pad_sz{k}(2):end) + mtimesx(samplesf{k}, permute(hf{k}, [3 4 1 2]), 'speed');

hello:
        Your work is great.Recently,I plan to implement your ECO using C++,but I met some problems about the variable ''sh'',I have a question of what it denotes in the lhs_operation_joint.m,and I wonder why you occur to implement the two steps.

**Comment by martin-danelljan** [comment]
Hi. The variable `sh` is actually just the Fourier coefficients of the target confidence scores on all the training samples. It is computed by multiplying the training samples `samplesf` with the filter `hf`. The loop and the index variable `k` goes over the different feature blocks.
