### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by deepConnectionism** [martin-danelljan/ECO#54]
>> install
 
... Build routine for mtimesx
... Checking for PC
... Finding path of mtimesx C source code files
... Found file mtimesx.c in D:\project\eco\ECO-master\ECO-master\external_libs\mtimesx\mtimesx.c
... Found file mtimesx_RealTimesReal.c in D:\project\eco\ECO-master\ECO-master\external_libs\mtimesx\mtimesx_RealTimesReal.c
Error using mtimesx_build (line 166)
A C/C++ compiler has not been selected with mex -setup

Error in install (line 10)
    mtimesx_build;

**Comment by martin-danelljan** [comment]
Just do what the error message tells you: Run `mex -setup`
