### ISSUE TITLE
the project didn't work for vot2016 dataset?

### ISSUE THREAD

**Issue by so-as** [martin-danelljan/ECO#8]
hi, I download the vot2016 datasets,  place some video  in the directory  sequences,  run the demo,   the program doesn't work. and I find the program has the setting: 'seq.format = otb,' I change it to 'vot', it does't work. how can I change the program? thx @cybertk @goutamgmb @martin-danelljan

**Comment by cybertk** [comment]
I tested with VOT dataset, even vot2017, they all worked fine. Please follow the guide in README.

**Comment by so-as** [comment]
oh, I see. I have successfully tested on the vot2016. But I means  using a single sequence of vot2016 in the demo_ECO_HC or GPU version needes to change some codes.  @cybertk

**Comment by martin-danelljan** [comment]
You can still run a single sequence using the VOT toolkit.

**Comment by so-as** [comment]
ok, I know what you mean.  thank you! @martin-danelljan
